// <auto-generated />
namespace _521H0049_521H0174.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class YourMigrationName8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YourMigrationName8));
        
        string IMigrationMetadata.Id
        {
            get { return "202312161656566_YourMigrationName8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
